<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1f7ea11b-71a5-438f-8a1f-0919a6fe8e8a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CyclingRoutes.Application\CyclingRoutes.Application.csproj" />
    <ProjectReference Include="..\CyclingRoutes.Contracts\CyclingRoutes.Contracts.csproj" />
    <ProjectReference Include="..\CyclingRoutes.Infrastructure\CyclingRoutes.Infrastructure.csproj" />
  </ItemGroup>

</Project>
